apiVersion: v1
kind: Namespace
metadata:
  name: obmovies
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: obmovies
  name: obmovies-app
  labels:
    k8s-app: obmovies-app
spec:
  selector:
      matchLabels:
        name: obmovies-app
  template:
    metadata:
      labels:
        name: obmovies-app
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      containers:
      - name: obmovies-app
        image: obmovies_app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        args:
        - python
        - run.py
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
